~~~ k8s script ~~~

$ ./run_kubernetes.sh

error: failed to create deployment: deployments.apps "udacity-devops-ml" already exists
NAME                                READY   STATUS    RESTARTS   AGE
udacity-devops-ml-78d865858-btr9x   1/1     Running   0          43s
Forwarding from 0.0.0.0:8000 -> 80
Handling connection for 8000


~~~ Prediction Output ~~~

$ ./make_prediction.sh

Port: 8000
{
  "prediction": [
    20.35373177134412
  ]
}


~~~ ML Api POD logs ~~~

$ kubectl logs udacity-devops-ml-78d865858-gdpfn -f

 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 148-616-134
[2022-11-21 16:13:22,156] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-11-21 16:13:22,164] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-11-21 16:13:22,170] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-11-21 16:13:22,173] INFO in app: Prediction values for received request: [20.35373177134412]
127.0.0.1 - - [21/Nov/2022 16:13:22] "POST /predict HTTP/1.1" 200 -